name: PR Quality Checks

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  python-quality:
    name: Python Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check code formatting (Black)
      run: black --check --diff .
    
    - name: Lint code (Ruff)
      run: ruff check .
    
    - name: Type check (MyPy)
      run: mypy . --ignore-missing-imports
    
    - name: Run quick tests
      run: python3 -m pytest -m "not slow" --maxfail=3

  frontend-quality:
    name: Frontend Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci
    
    - name: Check code formatting (Prettier)
      working-directory: frontend
      run: npm run format:check
    
    - name: Lint code (ESLint)
      working-directory: frontend
      run: npm run lint
    
    - name: Type check (TypeScript)
      working-directory: frontend
      run: npm run type-check
    
    - name: Build frontend
      working-directory: frontend
      run: npm run build